// Inlines the vendored AADE XSD files into a TypeScript module so the
// validator works the same way in Node and in the browser (no fs, no fetch).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export const MAIN = 'InvoicesDoc-v2.0.2.xsd';
export const PRELOAD = [
  'SimpleTypes-v2.0.2.xsd',
  'incomeClassification-v2.0.2.xsd',
  'expensesClassification-v2.0.2.xsd',
  'TransportTypes-v2.0.2.xsd',
];

export function render() {
  const file = (name) =>
    `  { fileName: ${JSON.stringify(name)}, contents: ${JSON.stringify(
      readFileSync(join(root, 'xsd', name), 'utf8'),
    )} }`;
  return [
    '// Generated by scripts/embed-xsd.mjs from ../../xsd/*.xsd. Do not edit.',
    '',
    'export interface XsdFile {',
    '  readonly fileName: string;',
    '  readonly contents: string;',
    '}',
    '',
    `export const MAIN_XSD: XsdFile =\n${file(MAIN)};`,
    '',
    `export const PRELOAD_XSDS: readonly XsdFile[] = [\n${PRELOAD.map(file).join(',\n')},\n];`,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = join(root, 'src', 'generated', 'xsd.ts');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, render());
}
